version: "3.5"
services:
  user-rest:
    image: thalasoft.com:5000/user-rest
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - user-rest
      - common
    volumes:
      - "~/dev/docker/projects/user-rest/volumes/code/user-rest-0.0.1-SNAPSHOT.jar:/tmp/user-rest/user-rest.jar"
      - "~/dev/docker/projects/common/volumes/logs:/tmp/user-rest/logs"
    environment:
      HOST_USER_ID: ${CURRENT_UID}
      HOST_GROUP_ID: ${CURRENT_GID}      
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: useraccount
      DB_USER: useraccount
    secrets:
      - DB_ROOT_PASSWORD
      - USER_REST_DB_PASSWORD
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3 
        window: 10s
    healthcheck:
      test: curl --fail --insecure https://localhost:8443/api/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3  
networks:
  user-rest:  
    name: user-rest
  common:  
    external: true
    name: common
secrets:
  DB_ROOT_PASSWORD:
    external: true
  USER_REST_DB_PASSWORD:
    external: true
